"use client";

import jsPDF from "jspdf";

import type { TrainingPilotSummaryRecord } from "@/lib/rkt-panel";

type GeneratePilotFpSummaryPdfInput = {
  generatedAt: Date;
  pilots: TrainingPilotSummaryRecord[];
  logoPath?: string;
};

async function loadImageDataUrl(path: string): Promise<string | null> {
  try {
    const response = await fetch(path);

    if (!response.ok) {
      return null;
    }

    const blob = await response.blob();

    return await new Promise<string | null>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(typeof reader.result === "string" ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function generatePilotFpSummaryPdf({
  generatedAt,
  pilots,
  logoPath = "/logos/logo_rkt.png",
}: GeneratePilotFpSummaryPdfInput) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = 210;
  const pageHeight = 297;
  const left = 12;

  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  const logoDataUrl = await loadImageDataUrl(logoPath);

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", left, 10, 20, 20);
  }

  doc.setTextColor(15, 15, 15);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.text("RESUMEN FP", logoDataUrl ? 36 : left, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Pilotos, número de FP y horario asignado", logoDataUrl ? 36 : left, 24);

  const formattedDate = generatedAt.toLocaleDateString("es-ES", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });

  doc.text(`Fecha: ${formattedDate}`, 198, 20, { align: "right" });

  const columns = [
    { title: "PILOTO", width: 74 },
    { title: "FP", width: 18 },
    { title: "HORARIOS", width: 94 },
  ] as const;

  function drawHeader(y: number) {
    let x = left;

    doc.setFillColor(245, 191, 36);
    doc.rect(left, y, 186, 8, "F");

    doc.setTextColor(20, 20, 20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.2);

    columns.forEach((column) => {
      doc.text(column.title, x + 1.5, y + 5.4);
      x += column.width;
    });
  }

  let cursorY = 38;
  drawHeader(cursorY);
  cursorY += 8;

  pilots.forEach((pilot, index) => {
    const scheduleText = pilot.sessions.map((session) => `${session.sessionName} · ${session.time}`).join(" | ");

    const rowCells = [pilot.pilotName, String(pilot.fpCount), scheduleText || "—"];
    const wrappedCells = rowCells.map((text, cellIndex) => doc.splitTextToSize(text, columns[cellIndex].width - 2));
    const maxLines = wrappedCells.reduce((best, lines) => Math.max(best, lines.length), 1);
    const rowHeight = Math.max(8, maxLines * 4.8 + 2.2);

    if (cursorY + rowHeight > 278) {
      doc.addPage();
      cursorY = 14;
      drawHeader(cursorY);
      cursorY += 8;
    }

    doc.setFillColor(index % 2 === 0 ? 248 : 241, index % 2 === 0 ? 248 : 241, index % 2 === 0 ? 248 : 241);
    doc.rect(left, cursorY, 186, rowHeight, "F");

    let x = left;
    doc.setTextColor(20, 20, 20);

    wrappedCells.forEach((lines, cellIndex) => {
      doc.setFont("helvetica", cellIndex === 1 ? "bold" : "normal");
      doc.setFontSize(cellIndex === 1 ? 10.2 : 9.2);
      doc.text(lines, x + 1.5, cursorY + 4.8);
      x += columns[cellIndex].width;
    });

    cursorY += rowHeight;
  });

  if (pilots.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90, 90, 90);
    doc.text("No hay pilotos asignados en este momento.", left, cursorY + 6);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(70, 70, 70);
  doc.text("Generated by RKT System", pageWidth / 2, 289, { align: "center" });

  const safeDate = generatedAt.toISOString().slice(0, 10);
  doc.save(`resumen-fp-pilotos-${safeDate}.pdf`);
}